### ISSUE TITLE
Gruppenbeitritt nicht auf die aktuellsten Werte

### ISSUE THREAD

**Issue by owlilicious** [hschat/app#74]
Szenario möglich: 

Klick auf Gruppenprofil --> Klick auf Gruppe beitreten --> abwarten --> währenddessen wird Passwort verändert --> Beitritt mit altem Passwort möglich

(Vgl. https://github.com/hschat/app/pull/64#discussion_r241957942)

**Comment by Totenfluch** [comment]
zusätzlich werden die Gruppenmitglieder mit einem alten Stand überschrieben

**Comment by lukasHoel** [comment]
Das Backend sollte das alles machen.
Vorschlag: neue Spalte "newParticipantID" in Chats, die gepatched wird. Des Backend joined dann die participants zusammen, wenn so ein Aufruf ankommt

**Comment by Totenfluch** [comment]
oder einfach eine methode die das macht... wozu ne spalte?

**Comment by Totenfluch** [comment]
https://github.com/hschat/app/pull/64/commits/14a3e81a4dbd95c35a15657aad063564e8ae1ccd
